FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY onnx_requirements.txt .

RUN pip install --no-cache-dir -r onnx_requirements-cpu.txt

COPY ./SDP/ /app/SDP

CMD ["/bin/bash"]